### ISSUE TITLE
关于OFDReader.class 中第97行xRes.getBaseLoc()为null的文件无法解析

### ISSUE THREAD

**Issue by shuzhiwangemail** [QAQtutu/ofdbox#4]
for (ST_Loc resLoc : xDocument.getCommonData().getDocumentRes()) {
                        resLoc.setParent(docRoot);
                        XRes xRes = OfdXmlUtils.toObject(fileManager.read(resLoc.getFullLoc()), XRes.class);
                        valid(xRes);
                        xRes.getBaseLoc().setParent(resLoc);
                        document.getRes().add(xRes);
                        if (!xRes.getBaseLoc().getLoc().endsWith("/")) {
                            xRes.getBaseLoc().setLoc(xRes.getBaseLoc().getLoc() + "/");
                        }
                    }
大神您好，我读取的ofd文件，在执行到xRes.getBaseLoc()的时候，我判断了下，读取到的为null。这种文件怎么转图片，请帮帮忙，非常感谢！

**Comment by QAQtutu** [comment]
提供一个原文件我看看

**Comment by shuzhiwangemail** [comment]
大神您好，	附件为我在测试过程中使用的文件，劳您费心了，谢谢！！----- 原始邮件 -----
发件人：QAQtutu <notifications@github.com>
收件人：QAQtutu/ofdbox <ofdbox@noreply.github.com>
抄送人：shuzhiwangemail <shuzhiwangemail@sina.com.cn>,  Author <author@noreply.github.com>
主题：Re:_[QAQtutu/ofdbox]_关于OFDReader.class_中第97行xRes.getBaseLoc()为null的文件无法解析_(#4)
日期：2020年11月10日 20点24分



提供一个原文件我看看

**Comment by QAQtutu** [comment]
OFD文件有两处不标准的地方，一是资源文件没有BaseLoc，一般会将资源单独放置在Res目录。二是发票中有个Path对象，没有LineWidth,同时又也没有绘制参数。以上两种情况刚刚做了兼容，第一个预设资源存储在资源Xml同目录，第二种给了默认值1。因为是不标准的文件，读取需要关闭OFDReder配置里的校验。目前可以转换成图片，但是ofdbox暂未实现绘制参数，转出来的发票章里的字是默认黑色，周末再实现。

**Comment by shuzhiwangemail** [comment]
非常感谢，谢谢！！
